services:
  mysql:
    image: mysql:8.0
    container_name: favourite-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: favourite_db
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    ports:
      - "3306:3306"